### ISSUE TITLE
ssr mode confict with nuxt 2.0 and webpack 4

### ISSUE THREAD

**Issue by daidi** [PeachScript/vue-infinite-loading#182]
`import InfiniteLoading from 'vue-infinite-loading/src/components/InfiniteLoading.vue';`

then:

× error node_modules\vue-infinite-loading\src\components\InfiniteLoading.vue:1
  (function (exports, require, module, __filename, __dirname) { <template>
  ^

  SyntaxError: Unexpected token <
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:152:10)
  at Module._compile (module.js:624:28)
  at Object.Module._extensions..js (module.js:671:10)
  at Module.load (module.js:573:32)
  at tryModuleLoad (module.js:513:12)
  at Function.Module._load (module.js:505:3)
  at Module.require (module.js:604:17)
  at require (internal/module.js:11:18)
  at r (\node_modules\vue-server-renderer\build.js:8341:16)
  at Object.vue-infinite-loading/src/components/InfiniteLoading.vue (server-bund
le.js:6173:18)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/
lib/index.js?!./pages/productlist.vue?vue&type=script&lang=js& (pages/productlist.vue?51e4:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../pages/productlist.vue?vue&type=script&lang=js& (pages/productlist.vue?db93:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../pages/productlist.vue (pages/productlist.vue:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at <anonymous>

**Comment by PeachScript** [comment]
The way in docs is not the best practice, you can use the `no-ssr` component of Nuxt to solve it: https://nuxtjs.org/api/components-no-ssr/#the-lt-no-ssr-gt-component

I will update this solution in the next doc version.
